SegmentTo59 <- [0-5][0-9] / [0-9]
SegmentTo23 <- [0-1][0-9] / '2' [0-3] / [0-9]
SegmentTo12 <- '0' [0-9] / '1' [0-2] / [0-9]
SegmentTo31 <- [0-2] [0-9] / '3' [0-1] / [0-9]
Month <- 'January' / 'February' / 'March' / 'April' / 'May' / 'June' / 'July' / 'August' / 'September' / 'October' / 'November' / 'December'

export Time <- {hours:SegmentTo23} ':' {minutes:SegmentTo59} ':' {seconds:SegmentTo59} / {minutes:SegmentTo59} ':' {seconds:SegmentTo59}
export Date <- {day: SegmentTo31} ' ' {month: Month} (','? (' ' {year: [0-9]^4}))? / {month: Month} ' '  {day: SegmentTo31} ('th' / 'rd' / 'st') (','? (' ' {year: [0-9]^4}))?

export DateTime <- Date Time